<a href="https://colab.research.google.com/github/varunSabnis/pytorch_course_udemy/blob/master/PyTorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch

In [0]:
import torch
import numpy as np

In [23]:
x = torch.tensor([1,2,3,4,5,6])
print("Tensor is {}".format(x))
print("Tensor datatype {}".format(x.dtype))

Tensor is tensor([1, 2, 3, 4, 5, 6])
Tensor datatype torch.int64


In [18]:
y = torch.FloatTensor([1,2,3,4,5,6])
print(y)
print(y.size())

tensor([1., 2., 3., 4., 5., 6.])
torch.Size([6])


In [26]:
x.view(3, -1) #implicit 2

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [30]:
a = np.array([1,2,3,4,5], dtype=np.float64)
b = torch.from_numpy(a)
print(b)
print(b.type())

tensor([1., 2., 3., 4., 5.], dtype=torch.float64)
torch.DoubleTensor


In [33]:
numpy_cnv = b.numpy()
print(numpy_cnv)

[1. 2. 3. 4. 5.]
