<a href="https://colab.research.google.com/github/varunSabnis/pytorch_course_udemy/blob/master/PyTorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip3 install torch

In [0]:
import torch
import numpy as np

In [4]:
x = torch.tensor([1,2,3,4,5,6])
print("Tensor is {}".format(x))
print("Tensor datatype {}".format(x.dtype))

Tensor is tensor([1, 2, 3, 4, 5, 6])
Tensor datatype torch.int64


In [5]:
y = torch.FloatTensor([1,2,3,4,5,6])
print(y)
print(y.size())

tensor([1., 2., 3., 4., 5., 6.])
torch.Size([6])


In [6]:
x.view(3, -1) #implicit 2

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [7]:
a = np.array([1,2,3,4,5], dtype=np.float64)
b = torch.from_numpy(a)
print(b)
print(b.type())

tensor([1., 2., 3., 4., 5.], dtype=torch.float64)
torch.DoubleTensor


In [8]:
numpy_cnv = b.numpy()
print(numpy_cnv)

[1. 2. 3. 4. 5.]


In [9]:
one_d = torch.arange(0, 9)
two_d = one_d.view(3,3)
print("Number of dimensions of tensor {}".format(two_d.dim()))
print("2D tensor {}".format(two_d))
print("Indexing 2d tensor at 1,2 - {}".format(two_d[1, 2]))

Number of dimensions of tensor 2
2D tensor tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
Indexing 2d tensor at 1,2 - 5


In [10]:
three_d = torch.arange(18).view(3,3,2)
three_d

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])

In [19]:
#slicing, indexing, segmenting
three_d[:2,0:2,0:1]
# three_d[1]
# three_d[1,:,0:1]
# three_d[1,:,:]

tensor([[[0],
         [2]],

        [[6],
         [8]]])

In [22]:
#matrix multiplication
mat_a = torch.tensor([1, 2, 3, 4, 5, 6]).view(2, 3)
mat_b = torch.tensor([1, 2, 3, 4, 5, 6]).view(3, 2)

res = torch.matmul(mat_a, mat_b)
print(res)

#simpler form
print(mat_a @ mat_b)

tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])
